version: "3"
services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: amagi
      POSTGRES_DB: library
    volumes:
      - ${PWD}/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - 6666:5432
    restart: always
  backend:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    environment:
      POSTGRES_URI: postgres://amagi@postgres/library
      BACKEND_PORT: 8080
      DEBUG: swagger2-koa:*
    restart:
      always
    volumes:
      - "${PWD}:/app"
    ports:
      - 8080:8080
    command: "yarn start"